
<?php



echo $block->sayHello();
?>


<style>

* {
  box-sizing: border-box;
}


/* .container{
  display: flex;
  align-items: center;
} */
body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Float four columns side by side */
.column {

  width: 50%;
  padding: 0 10px;
  margin-bottom: 20px;

  /* justify-content:center; */
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  border: thick double #32a1ce;
}

</style>


<button class="button" onclick="on_callPhp()">Get data</button>

<div id="main-container" class='container'>

</div>


<script>
  function on_callPhp() {
    fetch("https://jsonplaceholder.typicode.com/users/", {
        // mode:'no-cors',
        method: "GET",
        headers: {
            // 'Content-Type':'application/json',
            "Access-Control-Allow-Origin": "*",
            "Content-Type": "text/plain",
        },
    })
        .then((res) => res.json())
        .then((data) => {
            let output = "<h2>User details</h2>";

  

            
            data.forEach(function (data) {


                output += `
          <div class="row">
              <div class="column">
                  <div class="card">
                      <h3>
                          Name: ${data.name}
                      </h3>
                      <h3>
                          Address
                          </br>
                          ${data.address.suite}
                          ${data.address.street}
                          ${data.address.city}
                          ${data.address.zipcode}
                      </h3>
                      <h3>
                          Contact details
                          </br>
                          ${data.email}
                          ${data.phone}
                      </h3>
                  </div>
              </div>
          </div>
          `;
            });
            document.getElementById("main-container").innerHTML = output;
        })
        .catch((error) => console.log(error));


}

</script>


